### ISSUE TITLE
Ніби немає файлу pycashe

### ISSUE THREAD

**Issue by Olevsky-Ivan** [mate-academy/py-mutable-immutable#1056]
Ніби немає файлу pycashe

_Originally posted by @Olevsky-Ivan in https://github.com/mate-academy/py-mutable-immutable/issues/1054#issuecomment-1810249979_

**Comment by OleksandrKorolenko** [comment]
add file

**Comment by scandriy** [comment]
is this file located in ./app/__pycache__ ?
and how to upload it? Do I have to make another pull request?
